In [1]:
import numpy as np

In [2]:
# rows = students, columns = subjects
marks = np.array([
    [78, 82, 91, 67],
    [55, 61, 58, 60],
    [92, 88, 95, 90],
    [40, 45, 50, 42],
    [85, 79, 88, 91],
    [66, 70, 72, 68]
])

In [3]:
subjects = np.array(["Math", "Physics", "CS", "English"])

**Student Performance Metrics**

In [8]:
avg = np.mean(marks, axis=1)
avg

array([79.5 , 58.5 , 91.25, 44.25, 85.75, 69.  ])

In [9]:
std = np.std(marks, axis=1)
std

array([8.61684397, 2.29128785, 2.58602011, 3.76662979, 4.43705984,
       2.23606798])

In [10]:
max_mark = np.max(marks, axis=1)
max_mark

array([91, 61, 95, 50, 91, 72])

In [11]:
min_mark = np.min(marks, axis=1)
min_mark

array([67, 55, 88, 40, 79, 66])

**Student Ranking**

In [12]:
rank = np.argsort(-avg) + 1
rank 

array([3, 5, 1, 6, 2, 4])

**Pass / Fail Logic (Real Rule)**

In [13]:
pass_mask = np.all(marks >= 60, axis=1)
pass_mask

array([ True, False,  True, False,  True,  True])

**Grade System**

In [20]:
grades = np.where(
    avg >= 85, "A+",
    np.where(avg >= 75, "A",
    np.where(avg >= 60, "B", "F"))
)
grades

array(['A', 'F', 'A+', 'F', 'A+', 'B'], dtype='<U2')

**Scholarship Eligibility**

In [21]:
scholarship = (avg >= 80) & pass_mask
scholarship

array([False, False,  True, False,  True, False])

**Subject Difficulty Analysis**

In [22]:
subject_avg = np.mean(marks, axis=0)
subject_avg

array([69.33333333, 70.83333333, 75.66666667, 69.66666667])

In [23]:
hardest_subject = subjects[np.argmin(subject_avg)]
hardest_subject

np.str_('Math')

In [24]:
easiest_subject = subjects[np.argmax(subject_avg)]
easiest_subject

np.str_('CS')

**Identify At-Risk Students**

In [25]:
at_risk_students = np.where(avg < 60)[0]
at_risk_students

array([1, 3])

**Final Report**

In [26]:
report = np.column_stack((
    avg.round(2),
    grades,
    pass_mask,
    scholarship
))

print("Avg | Grade | Pass | Scholarship")
print(report)


Avg | Grade | Pass | Scholarship
[['79.5' 'A' 'True' 'False']
 ['58.5' 'F' 'False' 'False']
 ['91.25' 'A+' 'True' 'True']
 ['44.25' 'F' 'False' 'False']
 ['85.75' 'A+' 'True' 'True']
 ['69.0' 'B' 'True' 'False']]
