In [1]:
import numpy as np

In [2]:
# Categories: Food, Transport, Entertainment, Utilities
categories = np.array(["Food", "Transport", "Entertainment", "Utilities"])

In [3]:
days = np.arange(1, 11)  # Track 10 days
days

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
# Random daily expenses (rows = days, columns = categories)
np.random.seed(42)
expenses = np.random.randint(50, 500, size=(10, 4))

In [5]:
print("Expenses (per day per category):\n", expenses)

Expenses (per day per category):
 [[152 485 398 320]
 [156 121 238  70]
 [152 171 264 380]
 [137 422 149 409]
 [201 180 199 358]
 [307 393 463 343]
 [435 241 493 326]
 [210 363  71 302]
 [285 394  98 108]
 [219 237 320 239]]


**Total & Average Expense per Category**

In [6]:
total_per_category = np.sum(expenses, axis=0)

In [7]:
avg_per_category = np.mean(expenses, axis=0)

In [8]:
for cat, total, avg in zip(categories, total_per_category, avg_per_category):
    print(f"{cat}: Total = {total}, Average = {avg:.2f}")

Food: Total = 2254, Average = 225.40
Transport: Total = 3007, Average = 300.70
Entertainment: Total = 2693, Average = 269.30
Utilities: Total = 2855, Average = 285.50


**Highest & Lowest Expense**

In [9]:
max_expense = np.max(expenses)
min_expense = np.min(expenses)

In [10]:
max_pos = np.unravel_index(np.argmax(expenses), expenses.shape)
min_pos = np.unravel_index(np.argmin(expenses), expenses.shape)

In [11]:
print(f"Highest Expense: {max_expense} on Day {max_pos[0]+1}, Category: {categories[max_pos[1]]}")
print(f"Lowest Expense: {min_expense} on Day {min_pos[0]+1}, Category: {categories[min_pos[1]]}")

Highest Expense: 493 on Day 7, Category: Entertainment
Lowest Expense: 70 on Day 2, Category: Utilities


**Budget Exceed Alert**

In [12]:
budget = np.array([2000, 800, 1000, 1200])
exceed_mask = total_per_category > budget
exceed_categories = categories[exceed_mask]

In [13]:
print("Categories exceeding budget:", exceed_categories)

Categories exceeding budget: ['Food' 'Transport' 'Entertainment' 'Utilities']


**Daily Total & Average**

In [14]:
daily_total = np.sum(expenses, axis=1)
daily_avg = np.mean(expenses, axis=1)

In [15]:
for day, total, avg in zip(days, daily_total, daily_avg):
    print(f"Day {day}: Total = {total}, Average = {avg:.2f}")

Day 1: Total = 1355, Average = 338.75
Day 2: Total = 585, Average = 146.25
Day 3: Total = 967, Average = 241.75
Day 4: Total = 1117, Average = 279.25
Day 5: Total = 938, Average = 234.50
Day 6: Total = 1506, Average = 376.50
Day 7: Total = 1495, Average = 373.75
Day 8: Total = 946, Average = 236.50
Day 9: Total = 885, Average = 221.25
Day 10: Total = 1015, Average = 253.75


**Highest Spending Day**

In [16]:
max_day_index = np.argmax(daily_total)

In [17]:
print(f"Highest Spending Day: Day {days[max_day_index]} with {daily_total[max_day_index]} total expense")

Highest Spending Day: Day 6 with 1506 total expense
