In [1]:
import numpy as np

In [2]:
# Sample Matrices
A = np.array([[2, 3], [1, 4]])
B = np.array([[5, 2], [3, 1]])

In [3]:
print("Matrix A:\n", A)

Matrix A:
 [[2 3]
 [1 4]]


In [4]:
print("Matrix B:\n", B)

Matrix B:
 [[5 2]
 [3 1]]


**Addition & Subtraction**

In [5]:
add = A + B
sub = A - B

In [6]:
print("A + B:\n", add)

A + B:
 [[7 5]
 [4 5]]


In [7]:
print("A - B:\n", sub)

A - B:
 [[-3  1]
 [-2  3]]


**Matrix Multiplication**

In [8]:
mul = np.dot(A, B)  # or A @ B
print("A x B:\n", mul)

A x B:
 [[19  7]
 [17  6]]


**Transpose**

In [9]:
A_T = A.T
print("Transpose of A:\n", A_T)

Transpose of A:
 [[2 1]
 [3 4]]


**Determinant**

In [10]:
det_A = np.linalg.det(A)
print("Determinant of A:", det_A)

Determinant of A: 5.000000000000001


**Inverse (if exists)**

In [11]:
if det_A != 0:
    inv_A = np.linalg.inv(A)
    print("Inverse of A:\n", inv_A)
else:
    print("Matrix A is not invertible")

Inverse of A:
 [[ 0.8 -0.6]
 [-0.2  0.4]]


**Solve Linear Equations**

In [12]:
b = np.array([5, 6])
x = np.linalg.solve(A, b)
print("Solution of Ax = b:", x)

Solution of Ax = b: [0.4 1.4]


**Eigenvalues & Eigenvectors**

In [13]:
eig_vals, eig_vecs = np.linalg.eig(A)
print("Eigenvalues of A:", eig_vals)

Eigenvalues of A: [1. 5.]


In [14]:
print("Eigenvectors of A:\n", eig_vecs)

Eigenvectors of A:
 [[-0.9486833  -0.70710678]
 [ 0.31622777 -0.70710678]]
