In [1]:
import numpy as np

In [2]:
# Rows = cities, Columns = years (2018, 2019, 2020, 2021)
population = np.array([
    [500000, 520000, 540000, 560000],  # City 1
    [1200000, 1250000, 1300000, 1350000],  # City 2
    [800000, 790000, 780000, 770000],  # City 3 (declining)
    [300000, 320000, 340000, 360000],  # City 4
])

In [3]:
cities = np.array(["City1", "City2", "City3", "City4"])
years = np.array([2018, 2019, 2020, 2021])

**Total Population per Year**

In [4]:
total_per_year = np.sum(population, axis=0)
print("Total Population per Year:", total_per_year)

Total Population per Year: [2800000 2880000 2960000 3040000]


**Growth Rate per Year**

$$growth = \frac{pop_{year+1} - pop_{year}}{pop_{year}} \times 100$$

In [5]:
growth_rate = np.diff(population, axis=1) / population[:, :-1] * 100
print("Yearly Growth Rate (%) per City:\n", growth_rate.round(2))

Yearly Growth Rate (%) per City:
 [[ 4.    3.85  3.7 ]
 [ 4.17  4.    3.85]
 [-1.25 -1.27 -1.28]
 [ 6.67  6.25  5.88]]


**City with Highest / Lowest Population (Latest Year)**

In [6]:
latest_year_population = population[:, -1]
max_pop_city = cities[np.argmax(latest_year_population)]
min_pop_city = cities[np.argmin(latest_year_population)]

In [7]:
print(f"City with Highest Population (2021): {max_pop_city}")
print(f"City with Lowest Population (2021): {min_pop_city}")

City with Highest Population (2021): City2
City with Lowest Population (2021): City4


**Detect Declining Cities**

In [8]:
declining_mask = np.all(np.diff(population, axis=1) <= 0, axis=1)
declining_cities = cities[declining_mask]

In [9]:
print("Cities with Declining Population:", declining_cities)

Cities with Declining Population: ['City3']


**Average Population per City**

In [10]:
avg_population = np.mean(population, axis=1)
for city, avg in zip(cities, avg_population):
    print(f"{city} Average Population: {avg:.0f}")

City1 Average Population: 530000
City2 Average Population: 1275000
City3 Average Population: 785000
City4 Average Population: 330000
